apiVersion: v1
kind: Secret
metadata:
  name: cluster-example-db
type: Opaque
data:
  database: YXBw
---
apiVersion: v1
kind: Pod
metadata:
  name: psql-client
  labels:
    app: psql
spec:
  containers:
    - name: psql
      image: alpine/psql
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cluster-example-superuser
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cluster-example-superuser
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: cluster-example-db
              key: database
        - name: SERVICE_NAME
          value: cluster-example-rw.default.svc.cluster.local
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "250m"
      command: ["/bin/sh", "-c" ,"sleep 10000"]