#scheduledBackup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: daily-backup
spec:
  schedule: "0 29 6 * * *" # Every day at 6:29 AM
  backupOwnerReference: self
  cluster:
    name: cluster-example